### ISSUE TITLE
Questions about "GRID TENSOR PRODUCT"

### ISSUE THREAD

**Issue by liangzhixin-202169** [atomicarchitects/PriceofFreedom#3]
Hi! I have several questions about the grid tensor product. (1)Signal is projected to sphere directly, so how many points should be sampled in sphere? (2)How to choose quadrature method?(3) Dose it consume more memory than 2D fourier bases?

**Comment by mitkotak** [comment]
Hey sorry for the delay replying, regarding (3) should be similar though the 2D Fourier one currently doesn't use sparsity.

**Comment by xyuqing** [comment]
Hi, thanks for your interest in our work!
(1) Based on various sampling theorems, the number of points sampled scales as O(L^2) in order to perfectly reconstruct a spherical harmonic decomposition up to degree L. The table here summarizes this for various grid types
https://shtools.github.io/SHTOOLS/grid-formats.html#comparison-of-dh-and-glq-grids
(2) Generally Gauss-Legendre quadrature uses fewer points to achieve perfect fidelity so it should be faster
